### PR TITLE
Fix restoring selection

### LINKED ISSUE #459: When using a token from the backend and reloading, the token selection disappears
### What happened?

When a token from the backend is selected (eg. WTT on mainnet: https://dex.prd.aepps.com/swap?from=ct_KeTvHnhU85vuuQMMZocaiYkPL9tkoavDRT3Jsy47LK2YqLHYb&to=AE) and the page is opened / reloaded WTT is not selected.

### How can we reproduce it?

1. Go to https://dex.prd.aepps.com/swap?from=ct_KeTvHnhU85vuuQMMZocaiYkPL9tkoavDRT3Jsy47LK2YqLHYb&to=AE
2. WTT should be selected, its not

### Which device did this issue occur on?

Both

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Anything else you want us to know?

_No response_

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #459

### CODE REVIEW

File: src/mixins/saveTokenSelectionMixin.js [hunk 1]
```diff
@@ -72,20 +72,20 @@ export default {
...
+      const getToken = (token) => this.$store.getters['tokens/getAvailableTokens']().find(
         (_token) => (
           _token.is_ae && _token.symbol === token)
           || (!_token.is_ae && _token.contract_id === token),
       );
+      if ((from && !getToken(from)) || (to && !getToken(to))) {
+        await new Promise((resolve) => {
+          setTimeout(() => {
+            resolve();
+          }, 5000);
```
Comment (CedrikNikita) [inline src/mixins/saveTokenSelectionMixin.js:84]: Feel free to provide different timeout.

**Review by kenodressel — APPROVED** [review]
