### PR TITLE
fix: refresh page for non-default network and selected AE

### LINKED ISSUE #476: Refreshing the page (with selected tokens) shows "No liquidity pool" only on Testnet
### What happened?

If you are going to select not the default network (eg. Testnet) and select a pair of tokens that already have a liquidity pool, after refreshing the page, the tokens will be autoselected but it will show "No liquidity pool"

I assume has something in common with the fact of changing the network from default to a selected one

### How can we reproduce it?

refresh

### Which device did this issue occur on?

Desktop

### What browsers are you seeing the problem on?

Chrome

### Anything else you want us to know?

_No response_

### PR DESCRIPTION
**Pull request by bogdan-manole**
Fixes #476

### CODE REVIEW

File: src/mixins/saveTokenSelectionMixin.js [hunk 1]
```diff
@@ -73,9 +73,9 @@ export default {
         amount, isFrom,
       } = this.$route.query;
       const getToken = (token) => this.$store.getters['tokens/getAvailableTokens']().find(
-        (_token) => (
-          _token.is_ae && _token.symbol === token)
-          || (!_token.is_ae && _token.contract_id === token),
+        (_token) => (_token.is_ae
+          ? _token.symbol === token && _token.networkId === this.$store.state.networkId
+          : _token.contract_id === token),
```
Comment (kenodressel) [inline src/mixins/saveTokenSelectionMixin.js:78]: shouldn't we also check for network id here? could the same contract_id theoretically exist on two networks?

Comment (bogdan-manole) [reply src/mixins/saveTokenSelectionMixin.js:78]: I thought about it too, but is that a real case? I was thinking is like UUID, improbable to collide.
Anyway, I can change it.

Comment (bogdan-manole) [reply src/mixins/saveTokenSelectionMixin.js]: done

**Review by kenodressel — APPROVED** [review]
