### PR TITLE
fix(pool-view): filter provided liquidity by active network

### LINKED ISSUE #371: Ensure the imported liquidity is network specific

### PR DESCRIPTION
**Pull request by bogdan-manole**
Fixes #371 

How to test:

1) Import some liquidity you own on testnet
2) Do the same in mainnet  (if you don't have liquidity or tokens on mainnet, ping @bogdan-manole )
3) Switch between networks and see how the pool list is changing based on what network you have selected

network specific pools

### CODE REVIEW

File: src/store/modules/aeternity.js [hunk 1]
```diff
@@ -275,11 +279,15 @@ export default {
...
       rootState: { address },
+      rootGetters: { activeNetwork },
     }, {
       tokenA, tokenB,
       tokenASymbol, tokenBSymbol,
       tokenADecimals, tokenBDecimals,
     }) {
+      if (!activeNetwork) {
+        return null;
+      }
```
Comment (CedrikNikita) [inline src/store/modules/aeternity.js:290]:
```suggestion
      if (!activeNetwork) return null;
```

**Review by kenodressel — APPROVED** [review]
